/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CanvasCodeLinksPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  targetEditor: "vscode",
  customUriTemplate: "vscode://file/{path}:{line}:{col}",
  customCliCommand: 'code -g "{path}:{line}:{col}"',
  preferredRelativeRoot: "canvas",
  enableFallback: true,
  recognizedExtensions: [
    "cs",
    "ts",
    "js",
    "jsx",
    "tsx",
    "py",
    "cpp",
    "c",
    "h",
    "hpp",
    "rs",
    "go",
    "java",
    "kt",
    "swift",
    "rb",
    "php",
    "lua",
    "json",
    "yaml",
    "yml",
    "toml",
    "xml",
    "html",
    "css",
    "scss",
    "sh",
    "ps1",
    "sql",
    "md",
    "txt"
  ],
  decorateLinks: true,
  showNoticeOnOpen: true,
  mobileOpenMode: "viewer",
  mobileWebUrlTemplate: "https://github.com/OWNER/REPO/blob/main/{relpath}#L{line}"
};

// src/pathResolver.ts
var import_obsidian = require("obsidian");

// src/pathUtil.ts
var DRIVE = /^[a-zA-Z]:(\/|$)/;
function toPosix(p) {
  return p.replace(/\\/g, "/");
}
function isAbsolute(p) {
  const s = toPosix(p);
  return s.startsWith("/") || DRIVE.test(s);
}
function normalize(p) {
  let s = toPosix(p);
  let drive = "";
  const d = s.match(/^([a-zA-Z]:)(\/|$)/);
  if (d) {
    drive = d[1];
    s = s.slice(2);
  }
  const abs = s.startsWith("/");
  const out = [];
  for (const seg of s.split("/")) {
    if (!seg || seg === ".") continue;
    if (seg === "..") {
      if (out.length && out[out.length - 1] !== "..") out.pop();
      else if (!abs && !drive) out.push("..");
      continue;
    }
    out.push(seg);
  }
  const body = out.join("/");
  if (abs || drive) return drive + "/" + body;
  return body || ".";
}
function resolve(base, rel) {
  if (isAbsolute(rel)) return normalize(rel);
  return normalize((base || "/") + "/" + rel);
}
function join(...parts) {
  return normalize(parts.join("/"));
}
function dirname(p) {
  const n = normalize(p);
  const i = n.lastIndexOf("/");
  if (i < 0) return ".";
  if (i === 0) return "/";
  if (i === 2 && DRIVE.test(n)) return n.slice(0, 3);
  return n.slice(0, i);
}
function basename(p) {
  const s = toPosix(p).replace(/\/+$/, "");
  return s.substring(s.lastIndexOf("/") + 1);
}
function relative(from, to) {
  const a = normalize(from);
  const b = normalize(to);
  const da = a.match(/^[a-zA-Z]:/)?.[0].toLowerCase();
  const db = b.match(/^[a-zA-Z]:/)?.[0].toLowerCase();
  if (da !== db) return b;
  const as = a.split("/").filter((x) => x && !/^[a-zA-Z]:$/.test(x));
  const bs = b.split("/").filter((x) => x && !/^[a-zA-Z]:$/.test(x));
  let i = 0;
  while (i < as.length && i < bs.length && as[i] === bs[i]) i++;
  return [...as.slice(i).map(() => ".."), ...bs.slice(i)].join("/");
}

// src/pathResolver.ts
var PathResolver = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  /**
   * Get the absolute filesystem path of the vault root
   */
  getVaultBasePath() {
    if (import_obsidian.Platform.isMobile) return "/";
    const adapter = this.app.vault.adapter;
    if (adapter instanceof import_obsidian.FileSystemAdapter) {
      return adapter.getBasePath();
    }
    return adapter.basePath || "";
  }
  /** Vault-relative form of an absolute path, or null when it lies outside the vault */
  toVaultPath(absPath) {
    const n = normalize(absPath);
    const base = normalize(this.getVaultBasePath());
    const ci = /^[a-zA-Z]:/.test(n);
    const [nn, bb] = ci ? [n.toLowerCase(), base.toLowerCase()] : [n, base];
    if (bb === "/") return n.startsWith("/") ? n.slice(1) : null;
    if (nn === bb) return "";
    if (nn.startsWith(bb + "/")) return n.slice(base.length + 1);
    return null;
  }
  /** Does the file exist? fs on desktop, the vault adapter on mobile */
  async fileExists(absPath) {
    if (import_obsidian.Platform.isMobile) {
      const vp = this.toVaultPath(absPath);
      return vp ? this.app.vault.adapter.exists(vp) : false;
    }
    if (!import_obsidian.Platform.isDesktop) return false;
    try {
      const fs = require("fs");
      return fs.existsSync(absPath);
    } catch {
      return false;
    }
  }
  /**
   * Get the absolute filesystem directory of a given vault file (e.g. .canvas file)
   */
  getFileDirectory(file) {
    const vaultBase = this.getVaultBasePath();
    const fullFilePath = join(vaultBase, file.path);
    return dirname(fullFilePath);
  }
  /**
   * Parse a raw link string (from markdown [text](url), [[wikilink]], or canvas node)
   */
  parseLink(rawLink) {
    if (!rawLink || typeof rawLink !== "string") return null;
    let link = rawLink.trim();
    const mdMatch = link.match(/^\[([^\]]*)\]\(([^)]+)\)$/);
    if (mdMatch) {
      link = mdMatch[2].trim();
    }
    const wikiMatch = link.match(/^\[\[([^\]|]+)(?:\|[^\]]+)?\]\]$/);
    if (wikiMatch) {
      link = wikiMatch[1].trim();
    }
    let isExplicitCodeScheme = false;
    if (/^code:\/\//i.test(link)) {
      link = link.replace(/^code:\/\//i, "");
      isExplicitCodeScheme = true;
    } else if (/^code:/i.test(link)) {
      link = link.replace(/^code:/i, "");
      isExplicitCodeScheme = true;
    } else if (/^file:\/\//i.test(link)) {
      link = this.stripUriRoot(link.replace(/^file:\/\//i, ""));
      isExplicitCodeScheme = true;
    } else if (/^vscode:\/\/file(?=\/)/i.test(link)) {
      link = this.stripUriRoot(link.replace(/^vscode:\/\/file/i, ""));
      isExplicitCodeScheme = true;
    }
    try {
      link = decodeURIComponent(link);
    } catch {
    }
    let line = 1;
    let column = 1;
    let filePath = link;
    const queryMatch = filePath.match(/\?(?:.*&)?line=(\d+)(?:&(?:.*&)?col=(\d+))?/i);
    if (queryMatch) {
      line = parseInt(queryMatch[1], 10) || 1;
      if (queryMatch[2]) {
        column = parseInt(queryMatch[2], 10) || 1;
      }
      filePath = filePath.substring(0, filePath.indexOf("?"));
    }
    const hashMatch = filePath.match(/#(?:L)?(\d+)(?:[C:](\d+))?$/i);
    if (hashMatch) {
      line = parseInt(hashMatch[1], 10) || 1;
      if (hashMatch[2]) {
        column = parseInt(hashMatch[2], 10) || 1;
      }
      filePath = filePath.substring(0, filePath.lastIndexOf("#"));
    }
    const colonMatch = filePath.match(/(?<!^[a-zA-Z]):(\d+)(?::(\d+))?$/);
    if (colonMatch) {
      line = parseInt(colonMatch[1], 10) || 1;
      if (colonMatch[2]) {
        column = parseInt(colonMatch[2], 10) || 1;
      }
      filePath = filePath.substring(0, filePath.length - colonMatch[0].length);
    }
    filePath = filePath.trim();
    const extMatch = filePath.match(/\.([a-zA-Z0-9]+)$/);
    const ext = extMatch ? extMatch[1].toLowerCase() : "";
    const isRecognizedExt = this.settings.recognizedExtensions.map((e) => e.toLowerCase()).includes(ext);
    const isCodeLink = isExplicitCodeScheme || isRecognizedExt;
    return {
      originalLink: rawLink,
      filePath,
      line,
      column,
      isCodeLink
    };
  }
  /**
   * URI paths look like /C:/dir/x.cs on Windows (drop the slash) and /home/x.cs on POSIX (keep it)
   */
  stripUriRoot(p) {
    return /^\/[a-zA-Z]:[/]/.test(p) ? p.substring(1) : p;
  }
  /**
   * Resolve relative or absolute filePath to absolute path on disk
   */
  async resolveTarget(parsed, currentFile) {
    const vaultBase = this.getVaultBasePath();
    const rawPath = parsed.filePath;
    if (isAbsolute(rawPath)) {
      const exists = await this.fileExists(rawPath);
      return {
        resolvedPath: normalize(rawPath),
        line: parsed.line,
        column: parsed.column,
        exists,
        vaultPath: this.toVaultPath(rawPath),
        baseSource: exists ? "absolute" : "not_found"
      };
    }
    let canvasDir = "";
    if (currentFile) {
      canvasDir = this.getFileDirectory(currentFile);
    } else {
      canvasDir = vaultBase;
    }
    const preferredOrder = this.settings.preferredRelativeRoot === "canvas" ? ["canvas", "vault"] : ["vault", "canvas"];
    const resolveFromCanvas = async () => {
      const candidate = resolve(canvasDir, rawPath);
      return {
        path: candidate,
        exists: await this.fileExists(candidate)
      };
    };
    const resolveFromVault = async () => {
      const sanitized = rawPath.replace(/^(\.[/\\])+/, "");
      const candidate = resolve(vaultBase, sanitized);
      return {
        path: candidate,
        exists: await this.fileExists(candidate)
      };
    };
    let firstCandidatePath = "";
    for (const source of preferredOrder) {
      if (source === "canvas") {
        const res = await resolveFromCanvas();
        if (!firstCandidatePath) firstCandidatePath = res.path;
        if (res.exists) {
          return {
            resolvedPath: normalize(res.path),
            line: parsed.line,
            column: parsed.column,
            exists: true,
            vaultPath: this.toVaultPath(res.path),
            baseSource: "canvas"
          };
        }
      } else if (source === "vault") {
        const res = await resolveFromVault();
        if (!firstCandidatePath) firstCandidatePath = res.path;
        if (res.exists) {
          return {
            resolvedPath: normalize(res.path),
            line: parsed.line,
            column: parsed.column,
            exists: true,
            vaultPath: this.toVaultPath(res.path),
            baseSource: "vault"
          };
        }
      }
      if (!this.settings.enableFallback) {
        break;
      }
    }
    const missingPath = normalize(firstCandidatePath || resolve(canvasDir, rawPath));
    return {
      resolvedPath: missingPath,
      line: parsed.line,
      column: parsed.column,
      exists: false,
      vaultPath: this.toVaultPath(missingPath),
      baseSource: "not_found"
    };
  }
  /**
   * Calculate clean relative path from current canvas to target file on disk
   */
  makeRelativePath(fromCanvasFile, targetAbsoluteDiskPath) {
    const canvasDir = this.getFileDirectory(fromCanvasFile);
    let rel = relative(canvasDir, targetAbsoluteDiskPath);
    if (!rel.startsWith("./") && !rel.startsWith("../")) {
      rel = "./" + rel;
    }
    return rel;
  }
};

// src/editorLauncher.ts
var import_obsidian3 = require("obsidian");

// src/mobile.ts
function buildWebUrl(template, vaultPath, line, column) {
  if (!vaultPath || !template.trim() || /OWNER|REPO/.test(template)) return null;
  const encoded = vaultPath.split("/").map(encodeURIComponent).join("/");
  const filename = encodeURIComponent(vaultPath.substring(vaultPath.lastIndexOf("/") + 1));
  return template.replace(/\{relpath\}/g, encoded).replace(/\{filename\}/g, filename).replace(/\{line\}/g, String(line)).replace(/\{col\}/g, String(column));
}
function sliceLines(text, line, radius = 2e3) {
  const all = text.split(/\r?\n/);
  const target = Math.min(Math.max(line, 1), all.length);
  const start = Math.max(1, target - radius);
  const end = Math.min(all.length, target + radius);
  return { startLine: start, lines: all.slice(start - 1, end), total: all.length };
}

// src/codeViewerModal.ts
var import_obsidian2 = require("obsidian");
var CodeViewerModal = class extends import_obsidian2.Modal {
  constructor(app, vaultPath, line, column) {
    super(app);
    this.vaultPath = vaultPath;
    this.line = line;
    this.column = column;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("ccl-viewer");
    this.titleEl.setText(`${this.vaultPath}:${this.line}`);
    let text;
    try {
      text = await this.app.vault.adapter.read(this.vaultPath);
    } catch {
      new import_obsidian2.Notice(`Canvas Code Links: cannot read ${this.vaultPath}`);
      this.close();
      return;
    }
    const { startLine, lines } = sliceLines(text, this.line);
    const box = contentEl.createDiv({ cls: "ccl-viewer-code" });
    let targetEl = null;
    lines.forEach((content, i) => {
      const n = startLine + i;
      const row = box.createDiv({ cls: "ccl-viewer-line" });
      row.createSpan({ cls: "ccl-viewer-num", text: String(n) });
      row.createSpan({ cls: "ccl-viewer-text", text: content || " " });
      if (n === this.line) {
        row.addClass("ccl-viewer-target");
        targetEl = row;
      }
    });
    targetEl?.scrollIntoView({ block: "center" });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/editorLauncher.ts
function getNodeRequire() {
  if (typeof window === "undefined") return void 0;
  return window.require;
}
var EditorLauncher = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  /**
   * Open the resolved code target in the configured editor
   */
  async openTarget(target) {
    const filename = basename(target.resolvedPath);
    const { line, column, resolvedPath } = target;
    if (!target.exists) {
      new import_obsidian3.Notice(`Canvas Code Links: Warning! File not found on disk:
${resolvedPath}`, 6e3);
    }
    if (this.settings.showNoticeOnOpen) {
      new import_obsidian3.Notice(`Opening ${filename}:${line} in ${this.getEditorDisplayName()}...`, 2500);
    }
    if (import_obsidian3.Platform.isMobile) {
      return this.openOnMobile(target);
    }
    switch (this.settings.targetEditor) {
      case "vscode":
        return this.openInVSCode(resolvedPath, line, column);
      case "vscode_insiders":
        return this.openInVSCodeInsiders(resolvedPath, line, column);
      case "cursor":
        return this.openInCursor(resolvedPath, line, column);
      case "rider":
        return this.openInRider(resolvedPath, line, column);
      case "custom_uri":
        return this.openWithCustomUri(resolvedPath, line, column);
      case "custom_cli":
        return this.openWithCliCommand(resolvedPath, line, column);
      case "obsidian":
        return this.openInObsidian(resolvedPath, line, column);
      default:
        return this.openInVSCode(resolvedPath, line, column);
    }
  }
  /**
   * Mobile cannot launch desktop editors: show the file in-app, or open a web URL
   * (GitHub / github.dev / ...) built from the configured template.
   */
  async openOnMobile(target) {
    const { vaultPath, line, column } = target;
    if (this.settings.mobileOpenMode === "web_url") {
      const url = buildWebUrl(this.settings.mobileWebUrlTemplate, vaultPath, line, column);
      if (url) return this.openExternalUri(url);
      new import_obsidian3.Notice("Canvas Code Links: set your repository URL in plugin settings (Mobile). Using the built-in viewer.");
    }
    if (!target.exists) return false;
    if (!vaultPath) {
      new import_obsidian3.Notice("Canvas Code Links: file is outside the vault and cannot be opened on mobile.");
      return false;
    }
    new CodeViewerModal(this.app, vaultPath, line, column).open();
    return true;
  }
  getEditorDisplayName() {
    switch (this.settings.targetEditor) {
      case "vscode":
        return "VS Code";
      case "vscode_insiders":
        return "VS Code Insiders";
      case "cursor":
        return "Cursor";
      case "rider":
        return "JetBrains Rider";
      case "custom_uri":
        return "Custom URI";
      case "custom_cli":
        return "CLI Command";
      case "obsidian":
        return "Obsidian";
      default:
        return "Editor";
    }
  }
  /**
   * Format absolute path for vscode/cursor/electron URI schemes.
   * Ensures Windows paths like C:\foo\bar become /C:/foo/bar or compatible URI format.
   */
  formatUriPath(absPath) {
    let normalized = absPath.replace(/\\/g, "/");
    if (/^[a-zA-Z]:\//.test(normalized)) {
      normalized = "/" + normalized;
    }
    return encodeURI(normalized).replace(/#/g, "%23").replace(/\?/g, "%3F");
  }
  /**
   * Open URI with Electron shell or browser fallback
   */
  async openExternalUri(uri) {
    try {
      const nodeRequire = getNodeRequire();
      if (nodeRequire) {
        const { shell } = nodeRequire("electron");
        if (shell && shell.openExternal) {
          await shell.openExternal(uri);
          return true;
        }
      }
    } catch (e) {
      console.warn("Electron shell.openExternal failed, falling back to window.open", e);
    }
    try {
      window.open(uri);
      return true;
    } catch (err) {
      console.error("Failed to open URI:", uri, err);
      new import_obsidian3.Notice(`Failed to open link: ${uri}`);
      return false;
    }
  }
  async openInVSCode(absPath, line, col) {
    const formatted = this.formatUriPath(absPath);
    const uri = `vscode://file${formatted}:${line}:${col}`;
    const success = await this.openExternalUri(uri);
    if (!success) {
      return this.executeCli(`code -g "${absPath}:${line}:${col}"`);
    }
    return success;
  }
  async openInVSCodeInsiders(absPath, line, col) {
    const formatted = this.formatUriPath(absPath);
    const uri = `vscode-insiders://file${formatted}:${line}:${col}`;
    return this.openExternalUri(uri);
  }
  async openInCursor(absPath, line, col) {
    const formatted = this.formatUriPath(absPath);
    const uri = `cursor://file${formatted}:${line}:${col}`;
    return this.openExternalUri(uri);
  }
  async openInRider(absPath, line, col) {
    const uri = `jetbrains://rider/navigate/reference?path=${encodeURIComponent(absPath)}:${line}:${col}`;
    const success = await this.openExternalUri(uri);
    if (!success) {
      return this.executeCli(`rider64.exe --line ${line} "${absPath}"`);
    }
    return success;
  }
  async openWithCustomUri(absPath, line, col) {
    const uri = this.settings.customUriTemplate.replace(/\{path\}/g, absPath).replace(/\{uripath\}/g, this.formatUriPath(absPath)).replace(/\{line\}/g, String(line)).replace(/\{col\}/g, String(col));
    return this.openExternalUri(uri);
  }
  async openWithCliCommand(absPath, line, col) {
    const cmd = this.settings.customCliCommand.replace(/\{path\}/g, absPath).replace(/\{line\}/g, String(line)).replace(/\{col\}/g, String(col));
    return this.executeCli(cmd);
  }
  executeCli(command) {
    return new Promise((resolve2) => {
      try {
        const nodeRequire = getNodeRequire();
        if (nodeRequire) {
          const cp = nodeRequire("child_process");
          cp.exec(command, (err) => {
            if (err) {
              console.error("CLI exec error:", err);
              new import_obsidian3.Notice(`Failed to execute command: ${command}`);
              resolve2(false);
            } else {
              resolve2(true);
            }
          });
        } else {
          new import_obsidian3.Notice("Child process is not available in this environment.");
          resolve2(false);
        }
      } catch (e) {
        console.error("Failed to run CLI command:", e);
        resolve2(false);
      }
    });
  }
  async openInObsidian(absPath, line, col) {
    const adapter = this.app.vault.adapter;
    const { getBasePath } = adapter;
    const vaultBase = getBasePath ? getBasePath.call(adapter) : "";
    if (vaultBase && absPath.toLowerCase().startsWith(vaultBase.toLowerCase())) {
      const relVault = absPath.substring(vaultBase.length).replace(/^[\\/]+/, "").replace(/\\/g, "/");
      const file = this.app.vault.getAbstractFileByPath(relVault);
      if (file && "stat" in file) {
        const leaf = this.app.workspace.getLeaf(false);
        await leaf.openFile(file);
        const view = leaf.view;
        if (view && view.editor) {
          view.editor.setCursor({ line: Math.max(0, line - 1), ch: Math.max(0, col - 1) });
          view.editor.scrollIntoView({
            from: { line: Math.max(0, line - 1), ch: 0 },
            to: { line: Math.max(0, line - 1), ch: 0 }
          }, true);
        }
        return true;
      }
    }
    new import_obsidian3.Notice("File is outside vault or not recognized by Obsidian. Opening in system default...");
    return this.openExternalUri(`file:///${absPath.replace(/\\/g, "/")}`);
  }
};

// src/linkInterceptor.ts
var LinkInterceptor = class {
  constructor(app, settings, pathResolver, editorLauncher) {
    this.app = app;
    this.settings = settings;
    this.pathResolver = pathResolver;
    this.editorLauncher = editorLauncher;
  }
  /**
   * Global click handler attached with capture: true to intercept before Obsidian navigation
   */
  async handleClick(evt) {
    const target = evt.target;
    if (!target) return;
    const linkEl = target.closest("a, .canvas-code-link-badge, [data-code-link], .cm-link, .cm-url");
    if (!linkEl) return;
    const isEditorLink = !!linkEl.matches?.(".cm-link, .cm-url") && !linkEl.hasAttribute("href");
    if (isEditorLink && !(evt.ctrlKey || evt.metaKey)) return;
    let linkCandidate = "";
    if (linkEl.hasAttribute("data-code-link")) {
      linkCandidate = linkEl.getAttribute("data-code-link") || "";
    } else if (linkEl.hasAttribute("data-href")) {
      linkCandidate = linkEl.getAttribute("data-href") || "";
    } else if (linkEl.hasAttribute("href")) {
      linkCandidate = linkEl.getAttribute("href") || "";
    }
    if (!linkCandidate && (isEditorLink || linkEl.tagName.toLowerCase() === "a")) {
      const text = (linkEl.textContent?.trim() || "").replace(/^\(|\)$/g, "");
      if (text.match(/\.[a-zA-Z0-9]+(?::\d+|#L?\d+)/)) {
        linkCandidate = text;
      }
    }
    if (!linkCandidate) return;
    const parsed = this.pathResolver.parseLink(linkCandidate);
    if (!parsed || !parsed.isCodeLink) return;
    evt.preventDefault();
    evt.stopPropagation();
    evt.stopImmediatePropagation();
    const activeFile = this.app.workspace.getActiveFile();
    const resolved = await this.pathResolver.resolveTarget(parsed, activeFile);
    await this.editorLauncher.openTarget(resolved);
  }
  /**
   * Markdown post-processor to decorate code links inside Canvas cards and notes
   */
  markdownPostProcessor(el, ctx) {
    if (!this.settings.decorateLinks) return;
    const links = el.querySelectorAll("a.internal-link, a.external-link, a");
    links.forEach((a) => {
      const linkCandidate = a.getAttribute("data-href") || a.getAttribute("href") || "";
      const parsed = this.pathResolver.parseLink(linkCandidate);
      if (parsed && parsed.isCodeLink) {
        a.classList.add("canvas-code-link-badge");
        a.setAttribute("data-code-link", linkCandidate);
        a.setAttribute("title", `Open in ${this.settings.targetEditor.toUpperCase()} at line ${parsed.line}`);
        if (!a.querySelector(".code-icon")) {
          const iconSpan = createSpan({ cls: "code-icon" });
          const svg = iconSpan.createSvg("svg", {
            attr: {
              viewBox: "0 0 24 24",
              width: "14",
              height: "14",
              stroke: "currentColor",
              "stroke-width": "2",
              fill: "none",
              "stroke-linecap": "round",
              "stroke-linejoin": "round"
            }
          });
          svg.createSvg("polyline", { attr: { points: "16 18 22 12 16 6" } });
          svg.createSvg("polyline", { attr: { points: "8 6 2 12 8 18" } });
          a.prepend(iconSpan);
        }
      }
    });
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var CanvasCodeLinksSettingTab = class extends import_obsidian4.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("Default Code Editor").setDesc("The editor to launch when clicking a code link in Canvas or notes.").addDropdown((drop) => {
      drop.addOption("vscode", "Visual Studio Code (vscode://)").addOption("cursor", "Cursor (cursor://)").addOption("rider", "JetBrains Rider (jetbrains://rider)").addOption("vscode_insiders", "VS Code Insiders").addOption("obsidian", "Obsidian Internal Editor").addOption("custom_uri", "Custom URI Scheme").addOption("custom_cli", "Custom CLI Command").setValue(this.plugin.settings.targetEditor).onChange(async (v) => {
        const value = v;
        this.plugin.settings.targetEditor = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.targetEditor === "custom_uri") {
      new import_obsidian4.Setting(containerEl).setName("Custom URI Scheme Template").setDesc("Variables: {path} = full path, {uripath} = encoded uri path, {line} = line number, {col} = column number").addText((text) => {
        text.setPlaceholder("myeditor://open?file={path}&line={line}").setValue(this.plugin.settings.customUriTemplate).onChange(async (value) => {
          this.plugin.settings.customUriTemplate = value;
          await this.plugin.saveSettings();
        });
      });
    }
    if (this.plugin.settings.targetEditor === "custom_cli") {
      new import_obsidian4.Setting(containerEl).setName("Custom CLI Command Template").setDesc("Variables: {path} = full path, {line} = line number, {col} = column number").addText((text) => {
        text.setPlaceholder('code -g "{path}:{line}:{col}"').setValue(this.plugin.settings.customCliCommand).onChange(async (value) => {
          this.plugin.settings.customCliCommand = value;
          await this.plugin.saveSettings();
        });
      });
    }
    new import_obsidian4.Setting(containerEl).setName("Mobile (iOS / Android)").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Mobile open mode").setDesc("Desktop editors cannot be launched on mobile. Show the file in a built-in viewer, or open it on the web (GitHub, github.dev, ...). The code must be inside the vault (e.g. synced with Obsidian Git).").addDropdown((drop) => {
      drop.addOption("viewer", "Built-in code viewer (works offline)").addOption("web_url", "Open web URL (repository host)").setValue(this.plugin.settings.mobileOpenMode).onChange(async (v) => {
        this.plugin.settings.mobileOpenMode = v;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.mobileOpenMode === "web_url") {
      new import_obsidian4.Setting(containerEl).setName("Web URL template").setDesc("Variables: {relpath} = path inside the vault, {filename}, {line}, {col}. Replace OWNER/REPO/branch with yours.").addText((text) => {
        text.setPlaceholder("https://github.com/OWNER/REPO/blob/main/{relpath}#L{line}").setValue(this.plugin.settings.mobileWebUrlTemplate).onChange(async (value) => {
          this.plugin.settings.mobileWebUrlTemplate = value;
          await this.plugin.saveSettings();
        });
      });
    }
    new import_obsidian4.Setting(containerEl).setName("Preferred Path Resolution Root").setDesc("Where relative paths (like ./script.cs or ../src/script.cs) are resolved from first.").addDropdown((drop) => {
      drop.addOption("canvas", "Relative to current .canvas file folder (Recommended)").addOption("vault", "Relative to Vault / Repository Root").setValue(this.plugin.settings.preferredRelativeRoot).onChange(async (v) => {
        this.plugin.settings.preferredRelativeRoot = v;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Fallback Resolution").setDesc("If a file is not found relative to the .canvas directory, try searching relative to the Vault root.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.enableFallback).onChange(async (val) => {
        this.plugin.settings.enableFallback = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Recognized Code File Extensions").setDesc("Comma-separated extensions to identify as code links (e.g. cs, ts, js, py).").addTextArea((text) => {
      text.setPlaceholder("cs, ts, js, py, cpp, rs, go").setValue(this.plugin.settings.recognizedExtensions.join(", ")).onChange(async (val) => {
        const list = val.split(",").map((s) => s.trim().replace(/^\./, "")).filter(Boolean);
        this.plugin.settings.recognizedExtensions = list;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Decorate Code Links").setDesc("Render code links inside Canvas cards and notes with an icon and badge styling.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.decorateLinks).onChange(async (val) => {
        this.plugin.settings.decorateLinks = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Show Notification On Open").setDesc("Display an Obsidian Notice when launching a file at a specific line.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.showNoticeOnOpen).onChange(async (val) => {
        this.plugin.settings.showNoticeOnOpen = val;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/insertCodeModal.ts
var import_obsidian5 = require("obsidian");
var InsertCodeLinkModal = class extends import_obsidian5.Modal {
  constructor(app, settings, pathResolver, targetCanvasFile) {
    super(app);
    this.settings = settings;
    this.pathResolver = pathResolver;
    this.targetCanvasFile = targetCanvasFile;
  }
  filePath = "";
  line = 1;
  column = 1;
  title = "";
  format = "markdown";
  previewEl;
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("code-link-modal-content");
    this.titleEl.setText("Insert Code Link Card");
    const canvasName = this.targetCanvasFile ? this.targetCanvasFile.basename + ".canvas" : "No Canvas Active";
    contentEl.createEl("p", {
      text: `Context: ${canvasName} (paths will be calculated relative to this file)`,
      cls: "setting-item-description"
    });
    new import_obsidian5.Setting(contentEl).setName("Clipboard Import").setDesc("Quickly parse file and line from clipboard text").addButton((btn) => {
      btn.setButtonText("Paste from Clipboard").onClick(async () => {
        try {
          const clipText = await navigator.clipboard.readText();
          if (clipText) {
            this.parseAndApplyClipboard(clipText);
          } else {
            new import_obsidian5.Notice("Clipboard is empty.");
          }
        } catch (e) {
          new import_obsidian5.Notice("Failed to read clipboard: " + String(e));
        }
      });
    });
    new import_obsidian5.Setting(contentEl).setName("File Path").setDesc("Relative path (e.g. ./src/script.cs) or absolute path").addText((text) => {
      text.setPlaceholder("./src/script.cs").setValue(this.filePath).onChange((val) => {
        this.filePath = val.trim();
        this.updateAutoTitle();
        void this.updatePreview();
      });
    });
    new import_obsidian5.Setting(contentEl).setName("Line Number").setDesc("Target line number in the source file").addText((text) => {
      text.setPlaceholder("1").setValue(String(this.line)).onChange((val) => {
        this.line = parseInt(val, 10) || 1;
        this.updateAutoTitle();
        void this.updatePreview();
      });
    });
    new import_obsidian5.Setting(contentEl).setName("Card / Link Title").setDesc("Visible text on the card or link").addText((text) => {
      text.setPlaceholder("script.cs:42").setValue(this.title).onChange((val) => {
        this.title = val;
        void this.updatePreview();
      });
    });
    new import_obsidian5.Setting(contentEl).setName("Format Style").setDesc("Choose format for card or markdown link").addDropdown((drop) => {
      drop.addOption("markdown", "Markdown Link [file:line](./path:line)").addOption("card", "Rich Code Card (Heading + Badge)").addOption("protocol", "Code Protocol [file:line](code:./path:line)").setValue(this.format).onChange((val) => {
        this.format = val;
        void this.updatePreview();
      });
    });
    contentEl.createDiv({ text: "Generated Output Preview:", cls: "setting-item-name" });
    this.previewEl = contentEl.createDiv({ cls: "code-link-preview-box" });
    void this.updatePreview();
    new import_obsidian5.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Copy to Clipboard").onClick(() => {
        const content = this.generateOutputText();
        void navigator.clipboard.writeText(content);
        new import_obsidian5.Notice("Copied code link to clipboard!");
        this.close();
      });
    }).addButton((btn) => {
      btn.setButtonText("Insert into Canvas / Note").setCta().onClick(async () => {
        await this.insertIntoActiveView();
        this.close();
      });
    });
  }
  parseAndApplyClipboard(clipText) {
    const parsed = this.pathResolver.parseLink(clipText);
    if (parsed) {
      this.filePath = parsed.filePath;
      this.line = parsed.line;
      this.column = parsed.column;
      if (this.targetCanvasFile && isAbsolute(this.filePath)) {
        this.filePath = this.pathResolver.makeRelativePath(this.targetCanvasFile, this.filePath);
      }
      this.updateAutoTitle();
      this.onOpen();
      new import_obsidian5.Notice(`Parsed from clipboard: ${this.filePath}:${this.line}`);
    } else {
      this.filePath = clipText.trim();
      this.updateAutoTitle();
      this.onOpen();
    }
  }
  updateAutoTitle() {
    if (!this.filePath) return;
    const base = basename(this.filePath.replace(/\\/g, "/"));
    this.title = `${base}:${this.line}`;
  }
  generateOutputText() {
    const rawPath = this.filePath || "./script.cs";
    const lineSuffix = `:${this.line}`;
    const displayTitle = this.title || `${basename(rawPath)}:${this.line}`;
    if (this.format === "markdown") {
      return `[${displayTitle}](${rawPath}${lineSuffix})`;
    } else if (this.format === "protocol") {
      return `[${displayTitle}](code:${rawPath}${lineSuffix})`;
    } else {
      return `### \u{1F4C4} ${displayTitle}

[\u25B6 Open in VS Code](${rawPath}${lineSuffix})
`;
    }
  }
  previewSeq = 0;
  async updatePreview() {
    if (!this.previewEl) return;
    const seq = ++this.previewSeq;
    const text = this.generateOutputText();
    const parsed = this.pathResolver.parseLink(this.filePath + ":" + this.line);
    let status = "";
    if (parsed) {
      const resolved = await this.pathResolver.resolveTarget(parsed, this.targetCanvasFile);
      if (seq !== this.previewSeq) return;
      status = resolved.exists ? `

\u2713 Exists on disk: ${resolved.resolvedPath}` : `

\u26A0 File not yet found at: ${resolved.resolvedPath}`;
    }
    this.previewEl.setText(text + status);
  }
  async insertIntoActiveView() {
    const content = this.generateOutputText();
    const workspace = this.app.workspace;
    const activeView = workspace.getActiveViewOfType(import_obsidian5.ItemView);
    if (activeView && activeView.getViewType() === "canvas") {
      const canvas = activeView.canvas;
      if (canvas && typeof canvas.createTextNode === "function") {
        const center = canvas.viewport?.getCenter?.() || { x: 0, y: 0 };
        canvas.createTextNode({
          pos: { x: center.x - 120, y: center.y - 60 },
          size: { width: 280, height: 140 },
          text: content,
          save: true
        });
        new import_obsidian5.Notice("Added code link card to Canvas!");
        return;
      }
    }
    const mdView = workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (mdView && mdView.editor) {
      mdView.editor.replaceSelection(content);
      new import_obsidian5.Notice("Inserted code link into note!");
      return;
    }
    await navigator.clipboard.writeText(content);
    new import_obsidian5.Notice("Canvas editor not focused. Code link copied to clipboard!");
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var CanvasCodeLinksPlugin = class extends import_obsidian6.Plugin {
  settings = DEFAULT_SETTINGS;
  pathResolver;
  editorLauncher;
  linkInterceptor;
  async onload() {
    await this.loadSettings();
    this.pathResolver = new PathResolver(this.app, this.settings);
    this.editorLauncher = new EditorLauncher(this.app, this.settings);
    this.linkInterceptor = new LinkInterceptor(
      this.app,
      this.settings,
      this.pathResolver,
      this.editorLauncher
    );
    this.addSettingTab(new CanvasCodeLinksSettingTab(this.app, this));
    this.registerDomEvent(
      document,
      "click",
      (evt) => {
        void this.linkInterceptor.handleClick(evt);
      },
      true
      // Capture phase!
    );
    this.registerMarkdownPostProcessor((el, ctx) => {
      this.linkInterceptor.markdownPostProcessor(el, ctx);
    });
    this.addCommand({
      id: "insert-code-link-card",
      name: "Insert Code Link Card (or Relative Link)",
      callback: () => {
        const activeFile = this.app.workspace.getActiveFile();
        new InsertCodeLinkModal(this.app, this.settings, this.pathResolver, activeFile).open();
      }
    });
    this.addCommand({
      id: "copy-code-link-from-active-file",
      name: "Copy relative code link from active file",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            const vaultPath = activeFile.path.replace(/ /g, "%20").replace(/\(/g, "%28").replace(/\)/g, "%29");
            void navigator.clipboard.writeText(`[${activeFile.name}:1](${vaultPath}:1)`);
          }
          return true;
        }
        return false;
      }
    });
    this.registerObsidianProtocolHandler("canvas-code-link", async (params) => {
      const filePath = params["file"];
      const line = parseInt(params["line"] || "1", 10);
      const col = parseInt(params["col"] || "1", 10);
      if (filePath) {
        const activeFile = this.app.workspace.getActiveFile();
        const parsed = {
          originalLink: filePath,
          filePath,
          line,
          column: col,
          isCodeLink: true
        };
        const resolved = await this.pathResolver.resolveTarget(parsed, activeFile);
        await this.editorLauncher.openTarget(resolved);
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.pathResolver) {
      this.pathResolver = new PathResolver(this.app, this.settings);
    }
    if (this.editorLauncher) {
      this.editorLauncher = new EditorLauncher(this.app, this.settings);
    }
    if (this.linkInterceptor) {
      this.linkInterceptor = new LinkInterceptor(
        this.app,
        this.settings,
        this.pathResolver,
        this.editorLauncher
      );
    }
  }
};
