/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CanvasCodeLinksPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  targetEditor: "vscode",
  customUriTemplate: "vscode://file/{path}:{line}:{col}",
  customCliCommand: 'code -g "{path}:{line}:{col}"',
  preferredRelativeRoot: "canvas",
  enableFallback: true,
  recognizedExtensions: [
    "cs",
    "ts",
    "js",
    "jsx",
    "tsx",
    "py",
    "cpp",
    "c",
    "h",
    "hpp",
    "rs",
    "go",
    "java",
    "kt",
    "swift",
    "rb",
    "php",
    "lua",
    "json",
    "yaml",
    "yml",
    "toml",
    "xml",
    "html",
    "css",
    "scss",
    "sh",
    "ps1",
    "sql",
    "md",
    "txt"
  ],
  decorateLinks: true,
  showNoticeOnOpen: true
};

// src/pathResolver.ts
var path = __toESM(require("path"));
var fs = __toESM(require("fs"));
var import_obsidian = require("obsidian");
var PathResolver = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  /**
   * Get the absolute filesystem path of the vault root
   */
  getVaultBasePath() {
    const adapter = this.app.vault.adapter;
    if (adapter instanceof import_obsidian.FileSystemAdapter) {
      return adapter.getBasePath();
    }
    return adapter.basePath || "";
  }
  /**
   * Get the absolute filesystem directory of a given vault file (e.g. .canvas file)
   */
  getFileDirectory(file) {
    const vaultBase = this.getVaultBasePath();
    const fullFilePath = path.join(vaultBase, file.path);
    return path.dirname(fullFilePath);
  }
  /**
   * Parse a raw link string (from markdown [text](url), [[wikilink]], or canvas node)
   */
  parseLink(rawLink) {
    if (!rawLink || typeof rawLink !== "string") return null;
    let link = rawLink.trim();
    const mdMatch = link.match(/^\[([^\]]*)\]\(([^)]+)\)$/);
    if (mdMatch) {
      link = mdMatch[2].trim();
    }
    const wikiMatch = link.match(/^\[\[([^\]|]+)(?:\|[^\]]+)?\]\]$/);
    if (wikiMatch) {
      link = wikiMatch[1].trim();
    }
    let isExplicitCodeScheme = false;
    if (/^code:\/\//i.test(link)) {
      link = link.replace(/^code:\/\//i, "");
      isExplicitCodeScheme = true;
    } else if (/^code:/i.test(link)) {
      link = link.replace(/^code:/i, "");
      isExplicitCodeScheme = true;
    } else if (/^file:\/\/\/?/i.test(link)) {
      link = link.replace(/^file:\/\/\/?/i, "");
      isExplicitCodeScheme = true;
    } else if (/^vscode:\/\/file\//i.test(link)) {
      link = link.replace(/^vscode:\/\/file\//i, "");
      isExplicitCodeScheme = true;
    }
    try {
      link = decodeURIComponent(link);
    } catch {
    }
    let line = 1;
    let column = 1;
    let filePath = link;
    const queryMatch = filePath.match(/\?(?:.*&)?line=(\d+)(?:&(?:.*&)?col=(\d+))?/i);
    if (queryMatch) {
      line = parseInt(queryMatch[1], 10) || 1;
      if (queryMatch[2]) {
        column = parseInt(queryMatch[2], 10) || 1;
      }
      filePath = filePath.substring(0, filePath.indexOf("?"));
    }
    const hashMatch = filePath.match(/#(?:L)?(\d+)(?:[C:](\d+))?$/i);
    if (hashMatch) {
      line = parseInt(hashMatch[1], 10) || 1;
      if (hashMatch[2]) {
        column = parseInt(hashMatch[2], 10) || 1;
      }
      filePath = filePath.substring(0, filePath.lastIndexOf("#"));
    }
    const colonMatch = filePath.match(/(?<!^[a-zA-Z]):(\d+)(?::(\d+))?$/);
    if (colonMatch) {
      line = parseInt(colonMatch[1], 10) || 1;
      if (colonMatch[2]) {
        column = parseInt(colonMatch[2], 10) || 1;
      }
      filePath = filePath.substring(0, filePath.length - colonMatch[0].length);
    }
    filePath = filePath.trim();
    const extMatch = filePath.match(/\.([a-zA-Z0-9]+)$/);
    const ext = extMatch ? extMatch[1].toLowerCase() : "";
    const isRecognizedExt = this.settings.recognizedExtensions.map((e) => e.toLowerCase()).includes(ext);
    const isCodeLink = isExplicitCodeScheme || isRecognizedExt || line > 1;
    return {
      originalLink: rawLink,
      filePath,
      line,
      column,
      isCodeLink
    };
  }
  /**
   * Resolve relative or absolute filePath to absolute path on disk
   */
  resolveTarget(parsed, currentFile) {
    const vaultBase = this.getVaultBasePath();
    const rawPath = parsed.filePath;
    if (path.isAbsolute(rawPath) || /^[a-zA-Z]:[\\/]/.test(rawPath)) {
      const exists = fs.existsSync(rawPath);
      return {
        resolvedPath: path.normalize(rawPath),
        line: parsed.line,
        column: parsed.column,
        exists,
        baseSource: exists ? "absolute" : "not_found"
      };
    }
    let canvasDir = "";
    if (currentFile) {
      canvasDir = this.getFileDirectory(currentFile);
    } else {
      canvasDir = vaultBase;
    }
    const preferredOrder = this.settings.preferredRelativeRoot === "canvas" ? ["canvas", "vault"] : ["vault", "canvas"];
    const resolveFromCanvas = () => {
      const candidate = path.resolve(canvasDir, rawPath);
      return {
        path: candidate,
        exists: fs.existsSync(candidate)
      };
    };
    const resolveFromVault = () => {
      const sanitized = rawPath.replace(/^(\.[\/\\])+/, "");
      const candidate = path.resolve(vaultBase, sanitized);
      return {
        path: candidate,
        exists: fs.existsSync(candidate)
      };
    };
    let firstCandidatePath = "";
    for (const source of preferredOrder) {
      if (source === "canvas") {
        const res = resolveFromCanvas();
        if (!firstCandidatePath) firstCandidatePath = res.path;
        if (res.exists) {
          return {
            resolvedPath: path.normalize(res.path),
            line: parsed.line,
            column: parsed.column,
            exists: true,
            baseSource: "canvas"
          };
        }
      } else if (source === "vault") {
        const res = resolveFromVault();
        if (!firstCandidatePath) firstCandidatePath = res.path;
        if (res.exists) {
          return {
            resolvedPath: path.normalize(res.path),
            line: parsed.line,
            column: parsed.column,
            exists: true,
            baseSource: "vault"
          };
        }
      }
      if (!this.settings.enableFallback) {
        break;
      }
    }
    return {
      resolvedPath: path.normalize(firstCandidatePath || path.resolve(canvasDir, rawPath)),
      line: parsed.line,
      column: parsed.column,
      exists: false,
      baseSource: "not_found"
    };
  }
  /**
   * Calculate clean relative path from current canvas to target file on disk
   */
  makeRelativePath(fromCanvasFile, targetAbsoluteDiskPath) {
    const canvasDir = this.getFileDirectory(fromCanvasFile);
    let rel = path.relative(canvasDir, targetAbsoluteDiskPath);
    rel = rel.replace(/\\/g, "/");
    if (!rel.startsWith("./") && !rel.startsWith("../")) {
      rel = "./" + rel;
    }
    return rel;
  }
};

// src/editorLauncher.ts
var path2 = __toESM(require("path"));
var import_obsidian2 = require("obsidian");
var EditorLauncher = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  /**
   * Open the resolved code target in the configured editor
   */
  async openTarget(target) {
    const filename = path2.basename(target.resolvedPath);
    const { line, column, resolvedPath } = target;
    if (!target.exists) {
      new import_obsidian2.Notice(`Canvas Code Links: Warning! File not found on disk:
${resolvedPath}`, 6e3);
    }
    if (this.settings.showNoticeOnOpen) {
      new import_obsidian2.Notice(`Opening ${filename}:${line} in ${this.getEditorDisplayName()}...`, 2500);
    }
    switch (this.settings.targetEditor) {
      case "vscode":
        return this.openInVSCode(resolvedPath, line, column);
      case "vscode_insiders":
        return this.openInVSCodeInsiders(resolvedPath, line, column);
      case "cursor":
        return this.openInCursor(resolvedPath, line, column);
      case "rider":
        return this.openInRider(resolvedPath, line, column);
      case "custom_uri":
        return this.openWithCustomUri(resolvedPath, line, column);
      case "custom_cli":
        return this.openWithCliCommand(resolvedPath, line, column);
      case "obsidian":
        return this.openInObsidian(resolvedPath, line, column);
      default:
        return this.openInVSCode(resolvedPath, line, column);
    }
  }
  getEditorDisplayName() {
    switch (this.settings.targetEditor) {
      case "vscode":
        return "VS Code";
      case "vscode_insiders":
        return "VS Code Insiders";
      case "cursor":
        return "Cursor";
      case "rider":
        return "JetBrains Rider";
      case "custom_uri":
        return "Custom URI";
      case "custom_cli":
        return "CLI Command";
      case "obsidian":
        return "Obsidian";
      default:
        return "Editor";
    }
  }
  /**
   * Format absolute path for vscode/cursor/electron URI schemes.
   * Ensures Windows paths like C:\foo\bar become /C:/foo/bar or compatible URI format.
   */
  formatUriPath(absPath) {
    let normalized = absPath.replace(/\\/g, "/");
    if (/^[a-zA-Z]:\//.test(normalized)) {
      normalized = "/" + normalized;
    }
    return encodeURI(normalized).replace(/#/g, "%23").replace(/\?/g, "%3F");
  }
  /**
   * Open URI with Electron shell or browser fallback
   */
  async openExternalUri(uri) {
    try {
      if (typeof window !== "undefined" && window.require) {
        const { shell } = window.require("electron");
        if (shell && shell.openExternal) {
          await shell.openExternal(uri);
          return true;
        }
      }
    } catch (e) {
      console.warn("Electron shell.openExternal failed, falling back to window.open", e);
    }
    try {
      window.open(uri);
      return true;
    } catch (err) {
      console.error("Failed to open URI:", uri, err);
      new import_obsidian2.Notice(`Failed to open link: ${uri}`);
      return false;
    }
  }
  async openInVSCode(absPath, line, col) {
    const formatted = this.formatUriPath(absPath);
    const uri = `vscode://file${formatted}:${line}:${col}`;
    const success = await this.openExternalUri(uri);
    if (!success) {
      return this.executeCli(`code -g "${absPath}:${line}:${col}"`);
    }
    return success;
  }
  async openInVSCodeInsiders(absPath, line, col) {
    const formatted = this.formatUriPath(absPath);
    const uri = `vscode-insiders://file${formatted}:${line}:${col}`;
    return this.openExternalUri(uri);
  }
  async openInCursor(absPath, line, col) {
    const formatted = this.formatUriPath(absPath);
    const uri = `cursor://file${formatted}:${line}:${col}`;
    return this.openExternalUri(uri);
  }
  async openInRider(absPath, line, col) {
    const uri = `jetbrains://rider/navigate/reference?path=${encodeURIComponent(absPath)}:${line}:${col}`;
    const success = await this.openExternalUri(uri);
    if (!success) {
      return this.executeCli(`rider64.exe --line ${line} "${absPath}"`);
    }
    return success;
  }
  async openWithCustomUri(absPath, line, col) {
    let uri = this.settings.customUriTemplate.replace(/\{path\}/g, absPath).replace(/\{uripath\}/g, this.formatUriPath(absPath)).replace(/\{line\}/g, String(line)).replace(/\{col\}/g, String(col));
    return this.openExternalUri(uri);
  }
  async openWithCliCommand(absPath, line, col) {
    const cmd = this.settings.customCliCommand.replace(/\{path\}/g, absPath).replace(/\{line\}/g, String(line)).replace(/\{col\}/g, String(col));
    return this.executeCli(cmd);
  }
  executeCli(command) {
    return new Promise((resolve2) => {
      try {
        if (typeof window !== "undefined" && window.require) {
          const cp = window.require("child_process");
          cp.exec(command, (err) => {
            if (err) {
              console.error("CLI exec error:", err);
              new import_obsidian2.Notice(`Failed to execute command: ${command}`);
              resolve2(false);
            } else {
              resolve2(true);
            }
          });
        } else {
          new import_obsidian2.Notice("Child process is not available in this environment.");
          resolve2(false);
        }
      } catch (e) {
        console.error("Failed to run CLI command:", e);
        resolve2(false);
      }
    });
  }
  async openInObsidian(absPath, line, col) {
    const adapter = this.app.vault.adapter;
    const vaultBase = adapter.getBasePath ? adapter.getBasePath() : "";
    if (vaultBase && absPath.toLowerCase().startsWith(vaultBase.toLowerCase())) {
      let relVault = absPath.substring(vaultBase.length).replace(/^[\\/]+/, "").replace(/\\/g, "/");
      const file = this.app.vault.getAbstractFileByPath(relVault);
      if (file && "stat" in file) {
        const leaf = this.app.workspace.getLeaf(false);
        await leaf.openFile(file);
        const view = leaf.view;
        if (view && view.editor) {
          view.editor.setCursor({ line: Math.max(0, line - 1), ch: Math.max(0, col - 1) });
          view.editor.scrollIntoView({
            from: { line: Math.max(0, line - 1), ch: 0 },
            to: { line: Math.max(0, line - 1), ch: 0 }
          }, true);
        }
        return true;
      }
    }
    new import_obsidian2.Notice("File is outside vault or not recognized by Obsidian. Opening in system default...");
    return this.openExternalUri(`file:///${absPath.replace(/\\/g, "/")}`);
  }
};

// src/linkInterceptor.ts
var LinkInterceptor = class {
  constructor(app, settings, pathResolver, editorLauncher) {
    this.app = app;
    this.settings = settings;
    this.pathResolver = pathResolver;
    this.editorLauncher = editorLauncher;
  }
  /**
   * Global click handler attached with capture: true to intercept before Obsidian navigation
   */
  async handleClick(evt) {
    const target = evt.target;
    if (!target) return;
    const linkEl = target.closest("a, .canvas-code-link-badge, [data-code-link]");
    if (!linkEl) return;
    let linkCandidate = "";
    if (linkEl.hasAttribute("data-code-link")) {
      linkCandidate = linkEl.getAttribute("data-code-link") || "";
    } else if (linkEl.hasAttribute("data-href")) {
      linkCandidate = linkEl.getAttribute("data-href") || "";
    } else if (linkEl.hasAttribute("href")) {
      linkCandidate = linkEl.getAttribute("href") || "";
    }
    if (!linkCandidate && linkEl.tagName.toLowerCase() === "a") {
      const text = linkEl.textContent?.trim() || "";
      if (text.match(/\.[a-zA-Z0-9]+(?::\d+|#L?\d+)/)) {
        linkCandidate = text;
      }
    }
    if (!linkCandidate) return;
    const parsed = this.pathResolver.parseLink(linkCandidate);
    if (!parsed || !parsed.isCodeLink) return;
    evt.preventDefault();
    evt.stopPropagation();
    evt.stopImmediatePropagation();
    const activeFile = this.app.workspace.getActiveFile();
    const resolved = this.pathResolver.resolveTarget(parsed, activeFile);
    await this.editorLauncher.openTarget(resolved);
  }
  /**
   * Markdown post-processor to decorate code links inside Canvas cards and notes
   */
  markdownPostProcessor(el, ctx) {
    if (!this.settings.decorateLinks) return;
    const links = el.querySelectorAll("a.internal-link, a.external-link, a");
    links.forEach((a) => {
      const linkCandidate = a.getAttribute("data-href") || a.getAttribute("href") || "";
      const parsed = this.pathResolver.parseLink(linkCandidate);
      if (parsed && parsed.isCodeLink) {
        a.classList.add("canvas-code-link-badge");
        a.setAttribute("data-code-link", linkCandidate);
        a.setAttribute("title", `Open in ${this.settings.targetEditor.toUpperCase()} at line ${parsed.line}`);
        if (!a.querySelector(".code-icon")) {
          const iconSpan = document.createElement("span");
          iconSpan.className = "code-icon";
          iconSpan.innerHTML = `<svg viewBox="0 0 24 24" width="14" height="14" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline></svg>`;
          a.prepend(iconSpan);
        }
      }
    });
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var CanvasCodeLinksSettingTab = class extends import_obsidian3.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Canvas Code Links Settings" });
    new import_obsidian3.Setting(containerEl).setName("Default Code Editor").setDesc("The editor to launch when clicking a code link in Canvas or notes.").addDropdown((drop) => {
      drop.addOption("vscode", "Visual Studio Code (vscode://)").addOption("cursor", "Cursor (cursor://)").addOption("rider", "JetBrains Rider (jetbrains://rider)").addOption("vscode_insiders", "VS Code Insiders").addOption("obsidian", "Obsidian Internal Editor").addOption("custom_uri", "Custom URI Scheme").addOption("custom_cli", "Custom CLI Command").setValue(this.plugin.settings.targetEditor).onChange(async (value) => {
        this.plugin.settings.targetEditor = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.targetEditor === "custom_uri") {
      new import_obsidian3.Setting(containerEl).setName("Custom URI Scheme Template").setDesc("Variables: {path} = full path, {uripath} = encoded uri path, {line} = line number, {col} = column number").addText((text) => {
        text.setPlaceholder("myeditor://open?file={path}&line={line}").setValue(this.plugin.settings.customUriTemplate).onChange(async (value) => {
          this.plugin.settings.customUriTemplate = value;
          await this.plugin.saveSettings();
        });
      });
    }
    if (this.plugin.settings.targetEditor === "custom_cli") {
      new import_obsidian3.Setting(containerEl).setName("Custom CLI Command Template").setDesc("Variables: {path} = full path, {line} = line number, {col} = column number").addText((text) => {
        text.setPlaceholder('code -g "{path}:{line}:{col}"').setValue(this.plugin.settings.customCliCommand).onChange(async (value) => {
          this.plugin.settings.customCliCommand = value;
          await this.plugin.saveSettings();
        });
      });
    }
    new import_obsidian3.Setting(containerEl).setName("Preferred Path Resolution Root").setDesc("Where relative paths (like ./script.cs or ../src/script.cs) are resolved from first.").addDropdown((drop) => {
      drop.addOption("canvas", "Relative to current .canvas file folder (Recommended)").addOption("vault", "Relative to Vault / Repository Root").setValue(this.plugin.settings.preferredRelativeRoot).onChange(async (val) => {
        this.plugin.settings.preferredRelativeRoot = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Fallback Resolution").setDesc("If a file is not found relative to the .canvas directory, try searching relative to the Vault root.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.enableFallback).onChange(async (val) => {
        this.plugin.settings.enableFallback = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Recognized Code File Extensions").setDesc("Comma-separated extensions to identify as code links (e.g. cs, ts, js, py).").addTextArea((text) => {
      text.setPlaceholder("cs, ts, js, py, cpp, rs, go").setValue(this.plugin.settings.recognizedExtensions.join(", ")).onChange(async (val) => {
        const list = val.split(",").map((s) => s.trim().replace(/^\./, "")).filter(Boolean);
        this.plugin.settings.recognizedExtensions = list;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Decorate Code Links").setDesc("Render code links inside Canvas cards and notes with an icon and badge styling.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.decorateLinks).onChange(async (val) => {
        this.plugin.settings.decorateLinks = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Show Notification On Open").setDesc("Display an Obsidian Notice when launching a file at a specific line.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.showNoticeOnOpen).onChange(async (val) => {
        this.plugin.settings.showNoticeOnOpen = val;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/insertCodeModal.ts
var import_obsidian4 = require("obsidian");
var path3 = __toESM(require("path"));
var InsertCodeLinkModal = class extends import_obsidian4.Modal {
  constructor(app, settings, pathResolver, targetCanvasFile) {
    super(app);
    this.settings = settings;
    this.pathResolver = pathResolver;
    this.targetCanvasFile = targetCanvasFile;
  }
  filePath = "";
  line = 1;
  column = 1;
  title = "";
  format = "markdown";
  previewEl;
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("code-link-modal-content");
    this.titleEl.setText("Insert Code Link Card");
    const canvasName = this.targetCanvasFile ? this.targetCanvasFile.basename + ".canvas" : "No Canvas Active";
    contentEl.createEl("p", {
      text: `Context: ${canvasName} (paths will be calculated relative to this file)`,
      cls: "setting-item-description"
    });
    new import_obsidian4.Setting(contentEl).setName("Clipboard Import").setDesc("Quickly parse file and line from clipboard text").addButton((btn) => {
      btn.setButtonText("Paste from Clipboard").onClick(async () => {
        try {
          const clipText = await navigator.clipboard.readText();
          if (clipText) {
            this.parseAndApplyClipboard(clipText);
          } else {
            new import_obsidian4.Notice("Clipboard is empty.");
          }
        } catch (e) {
          new import_obsidian4.Notice("Failed to read clipboard: " + e);
        }
      });
    });
    const fileSetting = new import_obsidian4.Setting(contentEl).setName("File Path").setDesc("Relative path (e.g. ./src/script.cs) or absolute path").addText((text) => {
      text.setPlaceholder("./src/script.cs").setValue(this.filePath).onChange((val) => {
        this.filePath = val.trim();
        this.updateAutoTitle();
        this.updatePreview();
      });
    });
    new import_obsidian4.Setting(contentEl).setName("Line Number").setDesc("Target line number in the source file").addText((text) => {
      text.setPlaceholder("1").setValue(String(this.line)).onChange((val) => {
        this.line = parseInt(val, 10) || 1;
        this.updateAutoTitle();
        this.updatePreview();
      });
    });
    new import_obsidian4.Setting(contentEl).setName("Card / Link Title").setDesc("Visible text on the card or link").addText((text) => {
      text.setPlaceholder("script.cs:42").setValue(this.title).onChange((val) => {
        this.title = val;
        this.updatePreview();
      });
    });
    new import_obsidian4.Setting(contentEl).setName("Format Style").setDesc("Choose format for card or markdown link").addDropdown((drop) => {
      drop.addOption("markdown", "Markdown Link [file:line](./path:line)").addOption("card", "Rich Code Card (Heading + Badge)").addOption("protocol", "Code Protocol [file:line](code:./path:line)").setValue(this.format).onChange((val) => {
        this.format = val;
        this.updatePreview();
      });
    });
    contentEl.createEl("div", { text: "Generated Output Preview:", cls: "setting-item-name" });
    this.previewEl = contentEl.createEl("div", { cls: "code-link-preview-box" });
    this.updatePreview();
    new import_obsidian4.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Copy to Clipboard").onClick(() => {
        const content = this.generateOutputText();
        navigator.clipboard.writeText(content);
        new import_obsidian4.Notice("Copied code link to clipboard!");
        this.close();
      });
    }).addButton((btn) => {
      btn.setButtonText("Insert into Canvas / Note").setCta().onClick(async () => {
        await this.insertIntoActiveView();
        this.close();
      });
    });
  }
  parseAndApplyClipboard(clipText) {
    const parsed = this.pathResolver.parseLink(clipText);
    if (parsed) {
      this.filePath = parsed.filePath;
      this.line = parsed.line;
      this.column = parsed.column;
      if (this.targetCanvasFile && (path3.isAbsolute(this.filePath) || /^[a-zA-Z]:[\\/]/.test(this.filePath))) {
        this.filePath = this.pathResolver.makeRelativePath(this.targetCanvasFile, this.filePath);
      }
      this.updateAutoTitle();
      this.onOpen();
      new import_obsidian4.Notice(`Parsed from clipboard: ${this.filePath}:${this.line}`);
    } else {
      this.filePath = clipText.trim();
      this.updateAutoTitle();
      this.onOpen();
    }
  }
  updateAutoTitle() {
    if (!this.filePath) return;
    const base = path3.basename(this.filePath.replace(/\\/g, "/"));
    this.title = `${base}:${this.line}`;
  }
  generateOutputText() {
    const rawPath = this.filePath || "./script.cs";
    const lineSuffix = `:${this.line}`;
    const displayTitle = this.title || `${path3.basename(rawPath)}:${this.line}`;
    if (this.format === "markdown") {
      return `[${displayTitle}](${rawPath}${lineSuffix})`;
    } else if (this.format === "protocol") {
      return `[${displayTitle}](code:${rawPath}${lineSuffix})`;
    } else {
      return `### \u{1F4C4} ${displayTitle}

[\u25B6 Open in VS Code](${rawPath}${lineSuffix})
`;
    }
  }
  updatePreview() {
    if (!this.previewEl) return;
    const text = this.generateOutputText();
    const parsed = this.pathResolver.parseLink(this.filePath + ":" + this.line);
    let status = "";
    if (parsed) {
      const resolved = this.pathResolver.resolveTarget(parsed, this.targetCanvasFile);
      status = resolved.exists ? `

\u2713 Exists on disk: ${resolved.resolvedPath}` : `

\u26A0 File not yet found at: ${resolved.resolvedPath}`;
    }
    this.previewEl.setText(text + status);
  }
  async insertIntoActiveView() {
    const content = this.generateOutputText();
    const activeView = this.app.workspace.getActiveViewOfType?.(import_obsidian4.ItemView) || this.app.workspace.activeLeaf?.view;
    if (activeView && activeView.getViewType() === "canvas") {
      const canvas = activeView.canvas;
      if (canvas && typeof canvas.createTextNode === "function") {
        const center = canvas.viewport?.getCenter?.() || { x: 0, y: 0 };
        canvas.createTextNode({
          pos: { x: center.x - 120, y: center.y - 60 },
          size: { width: 280, height: 140 },
          text: content,
          save: true
        });
        new import_obsidian4.Notice("Added code link card to Canvas!");
        return;
      }
    }
    const mdView = this.app.workspace.getActiveViewOfType("markdown");
    if (mdView && mdView.editor) {
      mdView.editor.replaceSelection(content);
      new import_obsidian4.Notice("Inserted code link into note!");
      return;
    }
    await navigator.clipboard.writeText(content);
    new import_obsidian4.Notice("Canvas editor not focused. Code link copied to clipboard!");
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var CanvasCodeLinksPlugin = class extends import_obsidian5.Plugin {
  settings = DEFAULT_SETTINGS;
  pathResolver;
  editorLauncher;
  linkInterceptor;
  async onload() {
    await this.loadSettings();
    this.pathResolver = new PathResolver(this.app, this.settings);
    this.editorLauncher = new EditorLauncher(this.app, this.settings);
    this.linkInterceptor = new LinkInterceptor(
      this.app,
      this.settings,
      this.pathResolver,
      this.editorLauncher
    );
    this.addSettingTab(new CanvasCodeLinksSettingTab(this.app, this));
    this.registerDomEvent(
      document,
      "click",
      (evt) => {
        this.linkInterceptor.handleClick(evt);
      },
      true
      // Capture phase!
    );
    this.registerMarkdownPostProcessor((el, ctx) => {
      this.linkInterceptor.markdownPostProcessor(el, ctx);
    });
    this.addCommand({
      id: "insert-code-link-card",
      name: "Insert Code Link Card (or Relative Link)",
      callback: () => {
        const activeFile = this.app.workspace.getActiveFile();
        new InsertCodeLinkModal(this.app, this.settings, this.pathResolver, activeFile).open();
      }
    });
    this.addCommand({
      id: "copy-code-link-from-active-file",
      name: "Copy relative code link from active file",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            const relPath = `./${activeFile.name}:1`;
            navigator.clipboard.writeText(`[${activeFile.name}:1](${relPath})`);
          }
          return true;
        }
        return false;
      }
    });
    this.registerObsidianProtocolHandler("canvas-code-link", async (params) => {
      const filePath = params["file"];
      const line = parseInt(params["line"] || "1", 10);
      const col = parseInt(params["col"] || "1", 10);
      if (filePath) {
        const activeFile = this.app.workspace.getActiveFile();
        const parsed = {
          originalLink: filePath,
          filePath,
          line,
          column: col,
          isCodeLink: true
        };
        const resolved = this.pathResolver.resolveTarget(parsed, activeFile);
        await this.editorLauncher.openTarget(resolved);
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.pathResolver) {
      this.pathResolver = new PathResolver(this.app, this.settings);
    }
    if (this.editorLauncher) {
      this.editorLauncher = new EditorLauncher(this.app, this.settings);
    }
    if (this.linkInterceptor) {
      this.linkInterceptor = new LinkInterceptor(
        this.app,
        this.settings,
        this.pathResolver,
        this.editorLauncher
      );
    }
  }
};
